INSERT INTO "ShopProduct" ("id", "name", "slug", "description", "category", "priceCents", "stock", "imageUrl", "modelPhotoUrl", "badge", "active", "sortOrder", "updatedAt") VALUES
('shop_hoodie', 'ZekerFlex Everyday Hoodie', 'everyday-hoodie', 'Zware organic katoenmix, relaxed fit en geborduurd ZF-logo.', 'Kleding', 6900, 24, '/marketing/freelancer-at-work.jpg', '/marketing/freelancer-at-work.jpg', 'Bestseller', true, 1, CURRENT_TIMESTAMP),
('shop_overshirt', 'Field Overshirt', 'field-overshirt', 'Stevig overshirt voor onderweg, op locatie en tussen shifts door.', 'Kleding', 8900, 12, '/marketing/employer-hero.jpg', '/marketing/employer-hero.jpg', 'Nieuw', true, 2, CURRENT_TIMESTAMP),
('shop_bottle', 'Shift Bottle', 'shift-bottle', 'Dubbelwandig staal, 600 ml. Houdt je koffie warm en je focus scherp.', 'Werkdag', 2900, 48, '/marketing/team-shift.jpg', '/marketing/team-shift.jpg', 'Elke dag', true, 3, CURRENT_TIMESTAMP),
('shop_tote', 'Workday Tote', 'workday-tote', 'Ruime canvas tas voor laptop, lunch en alles wat je werkdag vraagt.', 'Werkdag', 2400, 36, '/marketing/employer-branch.jpg', '/marketing/employer-branch.jpg', 'Praktisch', true, 4, CURRENT_TIMESTAMP),
('shop_notes', 'Field Notes Set', 'field-notes-set', 'Drie premium notitieboeken voor plannen, uren en goede ideeën.', 'Werkdag', 1800, 60, '/marketing/app-phone.png', '/marketing/app-phone.png', 'Set van 3', true, 5, CURRENT_TIMESTAMP),
('shop_cap', 'ZF Core Cap', 'zf-core-cap', 'Ongevoerd, verstelbaar en klaar voor vroege starts.', 'Kleding', 3200, 28, '/marketing/hero-freelancer.jpg', '/marketing/hero-freelancer.jpg', 'Core', true, 6, CURRENT_TIMESTAMP),
('shop_welcome', 'Welcome Work Kit', 'welcome-work-kit', 'Bottle, notebook en tote in een geschenkdoos voor nieuwe collega’s.', 'Cadeaus', 5900, 18, '/marketing/team-shift.jpg', '/marketing/team-shift.jpg', 'Voor teams', true, 7, CURRENT_TIMESTAMP),
('shop_socks', 'Shift Socks · 2 pack', 'shift-socks-2-pack', 'Zachte, stevige sokken met subtiel ZekerFlex-detail.', 'Cadeaus', 1600, 72, '/marketing/freelancer-at-work.jpg', '/marketing/freelancer-at-work.jpg', 'Klein cadeau', true, 8, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;
