apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zekerflex-storage-rwx
  labels:
    app.kubernetes.io/name: zekerflex
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
