apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zekerflex
  labels:
    app.kubernetes.io/name: zekerflex
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.zekerflex.com
      secretName: zekerflex-tls
  rules:
    - host: app.zekerflex.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zekerflex-app
                port:
                  name: http
