-- Werkkleding & PBM voor de webshop — automatisch gekoppeld aan klussen
-- ("Dit heb je nodig voor deze klus"). Idempotent via slug-conflict.
INSERT INTO "ShopProduct" ("id","name","slug","description","category","priceCents","stock","imageUrl","modelPhotoUrl","badge","active","sortOrder","updatedAt") VALUES
('shop_wg_shoes_s3','Veiligheidsschoenen S3','veiligheidsschoenen-s3','Stalen neus, doortreedbescherming en antislipzool. Verplicht PBM in magazijn, bouw en productie.','Werk & PBM',4995,40,'/shifts/logistiek.jpg','/shifts/logistiek.jpg','Verplicht PBM',true,20,CURRENT_TIMESTAMP),
('shop_wg_shoes_s1p','Veiligheidssneakers S1P','veiligheidssneakers-s1p','Lichte, sportieve veiligheidsschoen met composiet neus. Voor lange sta- en loopdiensten.','Werk & PBM',5995,30,'/shifts/algemeen.jpg','/shifts/algemeen.jpg','Licht',true,21,CURRENT_TIMESTAMP),
('shop_wg_shoes_ob','Antislip werkschoenen OB','antislip-werkschoenen-ob','Vetdichte, antislip werkschoen voor horeca en keuken. SRC-gecertificeerd.','Werk & PBM',3495,36,'/shifts/horeca.jpg','/shifts/horeca.jpg','Horeca',true,22,CURRENT_TIMESTAMP),
('shop_wg_gloves_grip','Werkhandschoenen met grip (3 paar)','werkhandschoenen-grip','Ademende nitril-coating voor grip bij tillen, inpakken en sjouwen. Set van 3.','Werk & PBM',995,120,'/shifts/logistiek.jpg','/shifts/logistiek.jpg',NULL,true,23,CURRENT_TIMESTAMP),
('shop_wg_gloves_cut','Snijbestendige handschoenen niveau 5','snijbestendige-handschoenen','Cut level 5 (EN 388). Voor keuken, glas, metaal en afval.','Werk & PBM',1495,80,'/shifts/horeca.jpg','/shifts/horeca.jpg',NULL,true,24,CURRENT_TIMESTAMP),
('shop_wg_vest','Reflecterend veiligheidshesje','veiligheidshesje','EN ISO 20471 klasse 2. Zichtbaarheid tussen heftrucks, verkeer en op evenementen.','Werk & PBM',695,200,'/shifts/evenement.jpg','/shifts/evenement.jpg','Zichtbaarheid',true,25,CURRENT_TIMESTAMP),
('shop_wg_ear','Gehoorbescherming — oordoppen (10 paar)','gehoorbescherming-oordoppen','SNR 36 dB. Voor productie, bouw en luide evenementen.','Werk & PBM',795,150,'/shifts/bouw.jpg','/shifts/bouw.jpg',NULL,true,26,CURRENT_TIMESTAMP),
('shop_wg_glasses','Veiligheidsbril helder','veiligheidsbril-helder','Krasvast, anti-condens, EN 166. Voor stof, spatten en slijpwerk.','Werk & PBM',995,90,'/shifts/bouw.jpg','/shifts/bouw.jpg',NULL,true,27,CURRENT_TIMESTAMP),
('shop_wg_knee','Kniebeschermers (paar)','kniebeschermers','Voor schoonmaak, vloeren en installatiewerk. Passen in kniezakken.','Werk & PBM',1695,60,'/shifts/schoonmaak.jpg','/shifts/schoonmaak.jpg',NULL,true,28,CURRENT_TIMESTAMP),
('shop_wg_trousers','Werkbroek met kniezakken','werkbroek-kniezakken','Stevige werkbroek, verstevigde knieën, meerdere zakken. Zwart.','Werk & PBM',3995,44,'/shifts/bouw.jpg','/shifts/bouw.jpg',NULL,true,29,CURRENT_TIMESTAMP),
('shop_wg_jacket','Softshell werkjas','softshell-werkjas','Waterafstotend, winddicht en ademend. Voor buitenwerk en koele magazijnen.','Werk & PBM',5995,28,'/shifts/logistiek.jpg','/shifts/logistiek.jpg',NULL,true,30,CURRENT_TIMESTAMP),
('shop_wg_helmet','Veiligheidshelm wit','veiligheidshelm','EN 397, verstelbaar. Verplicht op de meeste bouwplaatsen.','Werk & PBM',1295,50,'/shifts/bouw.jpg','/shifts/bouw.jpg','Bouw',true,31,CURRENT_TIMESTAMP),
('shop_wg_vca','VCA Basisveiligheid — lesboek (NL)','vca-basis-boek','Compleet lesboek ter voorbereiding op het VCA Basis-examen. Veel opdrachtgevers vragen dit diploma.','Werk & PBM',2495,70,'/shifts/kantoor.jpg','/shifts/kantoor.jpg','Examen',true,32,CURRENT_TIMESTAMP),
('shop_wg_tshirt','Werk-T-shirt UV & zweet (2-pack)','werk-tshirt-2pack','Vochtregulerend, UV 40+. Set van 2 voor warme diensten en buitenwerk.','Werk & PBM',1995,100,'/shifts/algemeen.jpg','/shifts/algemeen.jpg',NULL,true,33,CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;
